image: docker:19.03.0
services:
  - docker:19.03.0-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

deploy:
  stage: deploy
  script:
    - docker build -t nginx-with-hugo .
    - docker rm -f tech-blog || true
    - docker run -itd -p 0.0.0.0:8288:80/tcp --name tech-blog nginx-with-hugo
  
